### ISSUE TITLE
[PE-D][Tester D] Person name can contain digits

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F14-2/tp#170]
## Current Behaviour

A person name can contain digits.

## Expected Behaviour

A person name should not contain digits.

## Steps to reproduce

1. We can edit a person's name to contain digits.
2. Enter `edit S1234567 n\12345`

![image.png](https://raw.githubusercontent.com/tituschewxj/ped/main/files/5a3c87cf-fab0-4caf-8286-2e58d1c7c38a.png)

3. The person has digits in their name.

## Why this is an issue

A person name should technically not contain digits, but digits could be contained in the name.

From the user guide, it only says special characters are allowed, but digits are not special characters.

![image.png](https://raw.githubusercontent.com/tituschewxj/ped/main/files/1d1dae6f-71f6-4bd1-962a-d74758da5f67.png)

## Suggested Change

Apply validation to names to prevent having numbers in a person's name.

Or update the documentation to reflect that digits are also allowed.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: tituschewxj/ped#2

**Comment by jiahui0309** [comment]
duplicate to #202
