### ISSUE TITLE
[PE-D][Tester B] ClinicMate Feature Flaw 4 (addnote feature restrictions)

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F14-2/tp#174]
In the example below, I was able to add multiple identical notes to the same person. 

![Screenshot 2024-04-05 at 3.22.44 PM.png](https://raw.githubusercontent.com/STELLA-LYE/ped/main/files/4d2d8af5-e2bc-46e0-b910-8c01344d48c8.png)

Perhaps there could be restrictions on the number of notes that could be added for each individual. Alternatively, perhaps the app can prevent users from adding repetitive notes to prevent cluttering of the system with repeated unused information.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: STELLA-LYE/ped#6

**Comment by drustanyjt** [comment]
Add to UG that notes can be repeated BY DESIGN.

**Comment by drustanyjt** [comment]
![image](https://github.com/AY2324S2-CS2103T-F14-2/tp/assets/110999129/343e7b61-f6b7-4b27-bb44-21b583083c85)
