### ISSUE TITLE
[PE-D][Tester D]  Cannot edit a person's note partially

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F14-2/tp#186]
## Current Issue

There is no command available to edit part of a person's note.

The closest available command is `addnote IC_NUMBER n\NOTE [-replace]`, which either replaces all the content in a person's note, or appends to the person's note.

## Expected Behaviour

There should be a command available to edit a certain line of a person's note.

## Why this is an issue

This is an issue on multilined notes. Doctors would typically want to have as much detail on a patient, and therefore would use the append feature, resulting in many multiline notes. In the event that the user wants to make changes to a certain line, it could be troublesome as the user has to replace the whole note and retype it out.

However, this **may not be desirable** if the user wants to keep some parts of the note, and remove some other parts of the note.

There is no easy way currently to edit **part of a note,** so this could be considered a feature flaw.

## Suggested Change

Allow the user to be able to edit only part of a note, by implementing a new command to allow line by line change of the note. 

In addition to that, we can include line numbers in the note panel for efficient reference of what line a certain note is on. 

This allows quick and easy editing of a note's content, on any line.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: tituschewxj/ped#5

**Comment by jiahui0309** [comment]
duplicate with #190
