### ISSUE TITLE
[PE-D][Tester D] Confusion on clearing entries

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F14-2/tp#192]
## Current Behaviour

Clearing all persons using the `clear` command, does not clear the notes panel.

## Expected Behaviour

Clearing all persons using the `clear` command, should also clear the notes panel.

## Steps to reproduce

1. Type `show S1234567A` into the command input box and press enter.

![image.png](https://raw.githubusercontent.com/tituschewxj/ped/main/files/e7c2bcea-8c68-4415-9c5b-9205d5b5bf8a.png)

2. Type `clear` into the command input box and press enter.

![image.png](https://raw.githubusercontent.com/tituschewxj/ped/main/files/8a612dc0-440e-4c43-9e93-25e94f62402c.png)

3. A similar image should appear:

![image.png](https://raw.githubusercontent.com/tituschewxj/ped/main/files/70365321-8407-447a-b1df-a64ad9e1f119.png)

## Why this is an issue

This might be an issue because the data is still present after clearing the data. A user would expect that clearing entries would clear all entries, along with their data.

If the data persists, the user may think that not all data is being cleared from the database, but is in fact stored somewhere on their device. Thus causing the confusion.

## Suggested Change

Entering the `clear` command should also clear the notes panel together with it.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: tituschewxj/ped#6

**Comment by jiahui0309** [comment]
add in faq
q: when will my note be cleared?
a: for now, `clear` or `delete` note command will not clear your note. the note will always correspond to the user who you last `find`
