### ISSUE TITLE
[PE-D][Tester A] No good way to find a patient

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F14-2/tp#197]
Find is too restrictive on needing IC. There may be cases where it is better to search for name, or even patient's notes. Right now, the only way is to scroll through the list if I do not have the IC.

Maybe find should allow for me to search for more fields/

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: LimZiJia/ped#13

**Comment by jiahui0309** [comment]
duplicate with #203
