### ISSUE TITLE
[PE-D][Tester C] Relative directory of `jar` and `json` not emphasised

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F14-2/tp#199]
In the UG, the relative directory of `jar` and `json` file is not emphasised when explaining how to use it on another computer.

![image.png](https://raw.githubusercontent.com/narwhalsilent/ped/main/files/3f76b2e6-1471-4190-86ab-b44aa4cfa8dc.png)

Inexperienced user might put both under the same directory and wonder why they lost their data.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: narwhalsilent/ped#11

**Comment by jiahui0309** [comment]
duplicate with #200
