### ISSUE TITLE
[PE-D][Tester A] addnote command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F14-2/tp#201]
`addnote s1234567a n\ -replace hi -replace` removes all notes not sure if that is intended.

![image.png](https://raw.githubusercontent.com/LimZiJia/ped/main/files/ecef1238-eff6-4931-a3c5-fcedfa1f0666.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: LimZiJia/ped#15

**Comment by drustanyjt** [comment]
Solution will be dubplicate of #211
