### ISSUE TITLE
[PE-D][Tester D] Log file still contains `AddressBook`

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F14-2/tp#205]
## Current Behaviour

The log file still contains `AddressBook`.

## Expected Behaviour

The log file should contain the application name `ClinicMate` in place of `AddressBook`.

## Steps to reproduce

1. Enter ` java -jar .\clinicmate.jar` into the command shell

![image.png](https://raw.githubusercontent.com/tituschewxj/ped/main/files/d7de3eb2-cdd3-4198-95b1-e9ff73a05e23.png)

2. Observe a similar output as below:

![image.png](https://raw.githubusercontent.com/tituschewxj/ped/main/files/cd1667ed-fbfd-4320-988a-41b40755fabb.png)

## Why this is an issue

If a more technically inclined user, such as a developer or a technician,  wants to find out more about what is going on and views the log file, the appearance of `AddressBook` may confuse them.

## Suggested Change

Update certain log strings so that `ClinicMate` is displayed, rather than `ContactBook`.

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: tituschewxj/ped#7

**Comment by drustanyjt** [comment]
Need to clarify with Prof if it can be changed. If not it'll be mentioned in the UG that the log file uses this.
