### ISSUE TITLE
Code reuse

### ISSUE THREAD

**Issue by tengcharmaine** [AY2324S2-CS2103T-F14-2/tp#257]

**Comment by Jayne1010** [comment]
Jayne - I had ChatGPT's assistance for HelpCommand code, documentation and UI edits done by me.

**Comment by jiahui0309** [comment]
JiaHui - I used the assistance of Github CoPilot for most of my code. I also used the assistance of ChatGPT mainly for documentation, UI edits for my code.

**Comment by drustanyjt** [comment]
Drustan - I had Github CoPilot's assistance for most of the code attributed to me. Including but not limited to functional code, test code, github workflow files, and documentation.
