### ISSUE TITLE
Create a Google Form for Gathering Interest

### ISSUE THREAD

**Issue by drustanyjt** [AY2324S2-CS2103T-F14-2/tp#54]
We should use a Google form to create a mailing list of interested parties. This is mostly for CS2101's presentation but should be put incorporated into our `README.md` and/or user guide as well.

**Comment by drustanyjt** [comment]
@jiahui0309 could you add the edit link here?

**Comment by jiahui0309** [comment]
link to the google form: https://docs.google.com/forms/d/e/1FAIpQLSdhsv0afLOwhto8Ov6CW9FqKSQyEJ-oprHHLmLS-d5ylGShmg/viewform?usp=sharing
