### ISSUE TITLE
Github release for version 1.2 and release notes

### ISSUE THREAD

**Issue by tengcharmaine** [AY2324S2-CS2103T-F14-2/tp#62]

**Comment by drustanyjt** [comment]
Draft Release: https://github.com/AY2324S2-CS2103T-F14-2/tp/releases/edit/untagged-a31addc9b6632f4316a6

**Comment by drustanyjt** [comment]
Released! https://github.com/AY2324S2-CS2103T-F14-2/tp/releases/tag/v1.2
I'll close the milestone now.
