### ISSUE TITLE
Possible QOL changes to fix

### ISSUE THREAD

**Issue by jiahui0309** [AY2324S2-CS2103T-F14-2/tp#87]
Just a food for thought

1. `addnote` uses i/IC n/NOTE while `edit` doesn't use 'i/' prefix
2. [good to have] edit notes such that users don't have to replace everything in case of mistakes
3. entering a non-existent IC will return an empty list for `addnote` whereas for `edit`, it won't change the person list 
4. entering a non-existent IC will print an error statement "0 persons listed" -> might want to have a different error statement informing users that the IC is non existent
5.  suitability of error messages? e.g. "find t0123456a hellooo" prints "IC number starts with one letter (S,T,F,G,M) followed by seven digits and one letter behind It is case insensitive. An example is S1234567A."
6. `delete t0123` will print the default delete command message -> should print `INVALID_IC_ERROR` message instead
7. possible to standardise error messages format 🙂 

if these are valid concerns, do let me know and I will open a separate issue for it

**Comment by drustanyjt** [comment]
These all seem pretty important. We should definitely aim to fix these in v1.3, though I'm not sure if we can do any by v1.2b.

**Comment by jiahui0309** [comment]
How about we keep these in mind and edit them while doing v1.3? @drustanyjt

**Comment by tengcharmaine** [comment]
I think another one is to **update the invalid format message for the add command to not have tag mentioned at all** since we are just going to remove tag. 

I tried removing it just now but i think its more complex than just removing it from the message. So might need more time to do.

**Comment by tengcharmaine** [comment]
Another one is to **increase the font size/have more colour contrast**. (This is more for 2101 ca2 presentation)
